path: C:\Users\marco\Desktop\BoatTracking
train: MarinaPictures\train
val: MarinaPictures\valid

# Number of classes
nc: 5

# Classes
names:
  0: aircraft
  1: boat
  2: skiff
  3: personal watercraft
  4: mark